### ISSUE TITLE
Custom element doesn't exist: weather-chart-card

### ISSUE THREAD

**Issue by daufinsyd** [Yevgenium/weather-chart-card#102]
Hello :)

I'm trying to add the card but I always get "Custom element doesn't exist: weather-chart-card".

I installed it using hacs and it appears in the resources, I even tried downloading it manually and adding it with different URLs but it still doesn't work.
![image](https://user-images.githubusercontent.com/1218113/166436470-b9626264-b15c-4f1e-893b-8bacfffebdd4.png)

The card is
```
type: custom:weather-chart-card
```

Am I doing something false ?
Thanks

**Comment by daufinsyd** [comment]
The cards are now working although I didn't change anything, not even a restart (except for the ones during my tests). ¯\_(ツ)_/¯

**Comment by ghost** [comment]
not working for me either after several restarts etc.

`Resources`: is looking for `/local/weather-chart-card.js` and that is what the .js is actually called (I saw this as a mismatch error on another issue).
