### ISSUE TITLE
Options undefined

### ISSUE THREAD

**Issue by Firesphere** [Yevgenium/weather-chart-card#117]
As of late, I'm getting the following error persistently:

`weather-chart-card.js:4100:16 TypeError: can't access property "borderSkipped", options is undefined`

**Comment by Firesphere** [comment]
This happens at multiple places, where the options from `this` are undefined, it seems that some data isn't properly copied over?

I also get an error that the namespace fails:
```
lineNumber: 6883
​
message: ""
​
name: "NS_ERROR_FAILURE"
```

**Comment by selfish** [comment]
I'm getting a similar thing, and the chart goes blank:

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/7327741/187930422-ec222ebc-3706-42df-8094-77f13e6c1b09.png">
<img width="466" alt="image" src="https://user-images.githubusercontent.com/7327741/187930467-ae9643f3-5891-4e1d-bf4e-6764d46b70d4.png">

**Comment by greendog99** [comment]
I updated the version of [chart.js ](https://www.chartjs.org) from 3.5.1 to 3.9.1 in the weather-chart-card and now it renders correctly in Firefox. I've submitted a pull request, but in the meantime you can get my fixed version at https://github.com/greendog99/weather-chart-card/releases

**Comment by selfish** [comment]
Thank you @greendog99!

**Comment by Flox-Muc** [comment]
Thank you @greendog99 also from my side! I love this card and I'm really happy that it works again.

**Comment by Firesphere** [comment]
Cheers @greendog99 !

**Comment by override80** [comment]
Today I upgraded to 2023.1 and I'm having the same problem :/

**Comment by Firesphere** [comment]
I have no issues on HA 2023.1...
