### ISSUE TITLE
Feature Request: Support Humidity Sensor Override

### ISSUE THREAD

**Issue by Hypfer** [Yevgenium/weather-chart-card#15]
Since there's a `temp` property which overrides the forecast with the currently measured data, it would make sense to extend this feature to humidity as well.

**Comment by Ahoui-group** [comment]
Humidity sensors may be in the form of sensor.humidity_1d, ensor.humidity_2d, ensor.humidity_3d,... in day mode or  sensor.humidity_1h, ensor.humidity_2h, ensor.humidity_3h,... for hourly mode.
