### ISSUE TITLE
Рекомендации по улучшению

### ISSUE THREAD

**Issue by Limych** [Yevgenium/weather-chart-card#17]
1. Стоит ли заморачиваться и делать свою локализацию, когда есть готовые локализации на намного больше языков, уже вшитые в Lovelace? Имхо, разумнее использовать их, посмотрев как они подтягиваются в [коде Weather Forecast Card](https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/cards/ha-weather-card.js)
1. Имхо, стоит заморочиться на оптимизации занимаемого картой места. В частности, справа от погодного значка и температуры пропадает много пустого места.
1. Имхо, данные о восходах-закатах полезны, но не являются информацией о погоде. Я сторонник того, чтобы их вообще удалить из карточки, либо сделать опциональными (отключенными по-умолчанию)
1. Очень не хватает информации о текущей погоде в текстовом виде, как это [сделано в Weather Forecast Card](https://www.home-assistant.io/lovelace/weather-forecast/). В то же время заголовок карты, имхо, будет мало кому нужен. Может быть стоит как-то с этим поработать?
1. Очень ценно будет, если будет возможность раскрашивать график в разные цвета, как это [сделано в Mini Graph Card](https://github.com/kalkih/mini-graph-card#dynamic-line-color)

Огромное спасибо за то, что уже сделано и успехов в дальнейшем развитии этого проекта. Чем смогу — помогу. :)

**Comment by conrad66** [comment]
6. Для нас все такие привычнее давление в mmHg а не в hPa.
Как это сделать в вашей карточке и ей подобным ?

**Comment by Limych** [comment]
> 1. Для нас все такие привычнее давление в mmHg а не в hPa.
>    Как это сделать в вашей карточке и ей подобным ?

А у меня показывает в mmHg. 🤷‍♂️ Не помню, как я это сделал. Видимо, мод какой-то.
