### ISSUE TITLE
Character missing when decimal point added on chart temperature

### ISSUE THREAD

**Issue by chrislolk** [Yevgenium/weather-chart-card#26]
When the chart's temperature axis is change to decimal values, the first character is not shown (too large for the display). E.g. with temperature 15.5 degrees, the "1" is not shown.

**Comment by scstraus** [comment]
I'm having this problem too since upgrading to 0.98.4:

![image](https://user-images.githubusercontent.com/7644023/64495323-ce543d80-d298-11e9-89a9-47bdf19660d9.png)

**Comment by brandondb1** [comment]
I have this too.  I think its when the temperature range is small - if the range is large, it only shows whole numbers, but when the range is small it shows 0.5's, which pushes the length of the text out too long and cuts off the tens and the sign (if minus)

**Comment by brandondb1** [comment]
After a bit of looking, on line 432, there is:
              scaleInstance.width = 30;
If you set the number higher (35 worked for me with minus teens; -14) it widens the space available for the axis numbers.

**Comment by chanyork** [comment]
> After a bit of looking, on line 432, there is:
> scaleInstance.width = 30;
> If you set the number higher (35 worked for me with minus teens; -14) it widens the space available for the axis numbers.

This doesn't work for me.  Any other solution for this?

**Comment by brandondb1** [comment]
Make sure you refresh / clear your cache.  F12, right click on reload button, purge cache.

**Comment by scstraus** [comment]
Works for me too. Sometimes I have to delete the .gz version of the card in the custom card folder to get it to acknowledge the changes in the .js file.
