### ISSUE TITLE
Lovelace page does not render when DarkSky is unavailable

### ISSUE THREAD

**Issue by Apipa169** [Yevgenium/weather-chart-card#29]
I have an issue with my Lovelace interface. I have your weather card on my main page showing data from DarkSky. But as soon as DarkSky is unavailable the Lovelace page won’t render at all.

This occurs on all devices and on every page with this card. 

When DarkSky is not available. The weather.darksky sensor state is unavailable and it has only a friendly name as attribute.

**Comment by DoloresHA** [comment]
This also occurs if you have a misconfigured weather entity. E.g. I made a typo when typing in my weather station, and the entire page went away.

I love the card though :)
