### ISSUE TITLE
Is there anyway to change the line/bar color?

### ISSUE THREAD

**Issue by ihaettypo** [Yevgenium/weather-chart-card#37]
Have tried to add configs to chartOptions with no lucks, what am I missing here?

```js
            pointRadius: 0.0,
            pointHitRadius: 5.0,
            fill: false,
          },
          {
            label: this.ll('precip'),
            type: 'bar',
            data: precip,
            yAxisID: 'PrecipAxis',
            backgroundColor: "#e755ba", //added this line, nothing happended
          },
        ]
      },
      options: {
        animation: {
```

**Comment by dskaplan** [comment]
I've turned this code up and down and I think it is being set in the ha-graph, I am pretty sure it is being set [here](https://github.com/home-assistant/frontend/blob/dev/src/components/entity/ha-chart-base.js#L537) and I don't see a way to edit it from the JS file.
