### ISSUE TITLE
Mode Daily or Hourly doesn't work

### ISSUE THREAD

**Issue by javamanxp** [Yevgenium/weather-chart-card#41]
Hi,
There is some problem with mode Daily or Hourly.
The graph is same but not header
See screenshot
![image](https://user-images.githubusercontent.com/65118781/89886664-458f0180-dbcd-11ea-93ab-67ada7b73cb5.png)

best regard
GG

**Comment by jrap1245** [comment]
I have same issue.
Thanks for help.

**Comment by G2G2G2G** [comment]
still doesn't work
