### ISSUE TITLE
Graph is not showing in Lovelace 0.115

### ISSUE THREAD

**Issue by ee02217** [Yevgenium/weather-chart-card#42]
Hi guys,

After the update to 0.115, the graph in the card stopped working. Does this happen to anyone else? 
This is the result:
![image](https://user-images.githubusercontent.com/60232595/93593296-c2bb4c80-f9ab-11ea-88ba-f33116e0f6b0.png)

The only error I have is the below:
```
ncaught (in promise) TypeError: Cannot read property 'language' of undefined
    at HTMLElement._formatTickValue (chunk.93de88efd85a8b7b4ec4.js:26957)
    at Object.tickFormatFunction (chunk.d9cbf2fe4e32a009641f.js:1)
    at Object.convertTicksToLabels (chunk.d9cbf2fe4e32a009641f.js:1)
    at Object.update (chunk.d9cbf2fe4e32a009641f.js:1)
    at Object.update (chunk.d9cbf2fe4e32a009641f.js:1)
    at chunk.d9cbf2fe4e32a009641f.js:1
    at Object.each (chunk.d9cbf2fe4e32a009641f.js:1)
    at Object.update (chunk.d9cbf2fe4e32a009641f.js:1)
    at tn.updateLayout (chunk.d9cbf2fe4e32a009641f.js:1)
    at tn.update (chunk.d9cbf2fe4e32a009641f.js:1)
```

And this is my card config:
```
current: true
details: true
entity: weather.dark_sky
forecast: true
graph: true
hide_precipitation: true
name: Lisbon
type: 'custom:weather-card'

```

**Comment by w00tl00ps** [comment]
I just updated to 0.115 and don't see the graph too.

**Comment by francisp2** [comment]
Same for me. No chart on 0.115.0 or 0.115.1

**Comment by fmonday** [comment]
Same on 0.115.1. I get an additional error, but I think that one is pre-existing. 

```
TypeError: undefined is not an object (evaluating 'this.weatherObj.attributes.forecast')
TypeError: undefined is not an object (evaluating 'this.hass.language')
```

**Comment by kbrohkahn** [comment]
Looks like that error is unrelated, I was digging through the HA git history and found a fix courtesy of @fancygaphtrn by making the following addition in the source js file.

> I previously used this in the html.
 `<ha-chart-base data="[[ChartData]]"></ha-chart-base>`
 Had to change to include the hass object to this.
 `<ha-chart-base hass="[[_hass]]" data="[[ChartData]]"></ha-chart-base>`

[Link to the breaking change](https://github.com/home-assistant/frontend/pull/6671)

**Comment by SiliconAvatar** [comment]
@kbrohkahn I saw that comment and tried it, but it doesnt seem to change anything. The chart lines still don't load and I get the same error.
Were you successful in having this modification fix the card?

**Comment by fancygaphtrn** [comment]
Make sure you clear the browser cache.

**Comment by SiliconAvatar** [comment]
> Make sure you clear the browser cache.

Yes, @fancygaphtrn, my broser cache is cleared.
I uninstalled this card from HACS, cleared cache until the card displayed an error that it was unavailable.
Forked this repo, made the edit, then added my version to HACS and installed it, cleared cache again. The new card from my own repo loads fine, but has the same issues of no line graph and and error in the log.

```
Cannot read property 'skip' of undefined
```

Did just this change alone fix it for you?

**Comment by fancygaphtrn** [comment]
I am running a forked version that I have modified.   What was the full error when you Inspect in chrome?

**Comment by fancygaphtrn** [comment]
I  forked on github and uploaded what I use.    I use NWS and have tested with others.   [https://github.com/fancygaphtrn/lovelace-weather-card-chart](https://github.com/fancygaphtrn/lovelace-weather-card-chart)

**Comment by SiliconAvatar** [comment]
@fancygaphtrn, thank you!

Thank you for confirming it worked for you. It still was giving me the exact same problem using your repository so I dug a bit deeper. It worked correctly when accessed by IP, but not via my domain. I had "Cache Assets" enabled on my nginx proxy server, so that was caching the old version even when my browser cache was cleared.

**Comment by SiliconAvatar** [comment]
Submitted the needed changes to this repo in [PR#43](https://github.com/Yevgenium/lovelace-weather-card-chart/pull/43).

**Comment by ee02217** [comment]
> Submitted the needed changes to this repo in [PR#43](https://github.com/Yevgenium/lovelace-weather-card-chart/pull/43).

Would you mind also doing the PR to this other card?
https://github.com/bobzer/weather-card

**Comment by Spirituss** [comment]
The same issue is in 2021.6.3

**Comment by scstraus** [comment]
> Would you mind also doing the PR to this other card?

You should probably ask the maintainer of that card in his repo, rather than the maintainers of a totally different repo.
