### ISSUE TITLE
Digits are clipped on the left side

### ISSUE THREAD

**Issue by artemyevav** [Yevgenium/weather-chart-card#48]
![image](https://user-images.githubusercontent.com/40710570/99143039-bb868700-265a-11eb-896a-29de7e92b2de.png)
HA 0.117.6 both in Chrome and IOS app.

**Comment by scstraus** [comment]
#26

**Comment by chanyork** [comment]
Same as mine with the newest version.  Any fix for it.

![image](https://user-images.githubusercontent.com/28833849/107336556-31807a00-6af4-11eb-8bc9-e258a9dd26fe.png)

**Comment by scstraus** [comment]
See link above your post.
