### ISSUE TITLE
Bad card margin when title is not used

### ISSUE THREAD

**Issue by andras-tim** [Yevgenium/weather-chart-card#56]
If I don't want to specify the title, the card will have a bad margin and "merges" with the previous.

Bad behavior w/o title:
![Screenshot_2021-05-23_11-57-27](https://user-images.githubusercontent.com/619016/119255936-84bb9b80-bbbe-11eb-88a6-6a64e6b3ee17.png)

Expected behavior:
![Screenshot_2021-05-23_11-57-35](https://user-images.githubusercontent.com/619016/119255961-9d2bb600-bbbe-11eb-842a-a276dc2122f2.png)

**Comment by scstraus** [comment]
Unfortunately the developer isn't really actively maintaining this card and the header has never really worked properly. I use custom:card-mod as a workaround for this problem with the style parameter like so:

      - type: 'custom:weather-card-chart'
        style: |
          .card-header {
            padding: 20px 16px 10px;
            line-height: 32px;
          }
        title: Weather
        weather: weather.smartweather_home
        sun: sun.sun
        mode: hourly
        temp: sensor.smartweatherudp_temperature
        wind: sensor.smartweather_wind_gust
