### ISSUE TITLE
Graph in the card stopped working

### ISSUE THREAD

**Issue by Spirituss** [Yevgenium/weather-chart-card#63]
Hello!

From one of the last updates (2021.5 or 2021.6) the graph in the card stopped working. 
This is the result:
<img width="487" alt="Снимок экрана 2021-08-05 в 20 52 20" src="https://user-images.githubusercontent.com/47206760/128381411-5f42c64c-1d00-450b-9855-cacc86e9b6ca.png">

Is the any solution for this?

P.S. It works well in Hassio, but not in HA Core

**Comment by Spirituss** [comment]
Works again in 2021.8.2

**Comment by scstraus** [comment]
> Works again in 2021.8.2

Really? With the old graph code it works again? I'd go back to the old version again because with my changes, the new version looks a bit wonky now.

**Comment by Spirituss** [comment]
> > Works again in 2021.8.2
> 
> Really? With the old graph code it works again? I'd go back to the old version again because with my changes, the new version looks a bit wonky now.

Not sure. I copied js file from reserve HA instance. Possibly, it does the matter.

**Comment by RonnyWinkler** [comment]
For me, the graph stopped working with the update of this card from 0.2.7 to 0.2.8.
I downgraded this card to 0.2.7 and the graph is back again (on an old 2021.03? HA version) - so it has nothing depending on the new HA updates fo rme.

**Comment by carvalr** [comment]
Same issue here. I had to remove the old version, clear the cached frontend files (desktop and mobile) and after I applied the version 1.0.2 it is now working properly again.

**Comment by RonnyWinkler** [comment]
I updated to HA 2021.9.x and this card to version 1.0.2.
In HACS the card is marked red with title "not loaded"
The weather data is displayed without the graph:

![Screenshot_20210919-100125_Home Assistant](https://user-images.githubusercontent.com/49495550/133920096-604e7b11-c236-4206-a7ef-c27198594433.jpg)

The log shows this error:

![Screenshot_20210919-100147_Home Assistant](https://user-images.githubusercontent.com/49495550/133920111-bef83345-b984-4532-a10f-0acee1baad27.jpg)

Older card versions are shown in HACS without error but don't display the chart, too.
Weather provider is DWD integration (HACS).

**Comment by Yevgenium** [comment]
> I updated to HA 2021.9.x and this card to version 1.0.2.

The screenshot shows the old version of the card. Try clearing your browser cache.

**Comment by RonnyWinkler** [comment]
Tried this in Firefox yesterday. Cleared cache and all other stuff including Cookies. Restarted Browser. No difference. Tried in other browsers, too. I will check this again. Thanks.

**Comment by Yevgenium** [comment]
@RonnyWinkler 
Also note that the name of the card has changed. It is `weather-chart-card` now.

**Comment by RonnyWinkler** [comment]
> @RonnyWinkler
> Also note that the name of the card has changed. It is `weather-chart-card` now.

This point I missed. Some tries later (reinstalled the chart, restarted HA, it was recognized in Lovelace.
Thanks for the hint.

![Screenshot_20210919-125832_Home Assistant](https://user-images.githubusercontent.com/49495550/133925122-cbfaad73-42ef-40e2-b55f-b280310d81ca.jpg)

btw. Is there a possibility to define languange depending captions for the current weather ("Sunny" in the screenshot)?

**Comment by tomlut** [comment]
Anyone having issues with this card in 2021.11.4?

When I move the card from one view to another, the graph shows up in most vies but not all. 

Cache cleared. No difference. It just refuses to show the graph in some views.
