### ISSUE TITLE
HACS integration stopped working

### ISSUE THREAD

**Issue by artemyevav** [Yevgenium/weather-chart-card#64]
Maybe "filename" in the config is wrong
https://github.com/Yevgenium/weather-chart-card/blob/0c16ee74a90c8b0902d4a989d883f9d2207331c7/hacs.json#L4

**Comment by gdreelin** [comment]
Mine also stopped working right but also notice the .js file is named different than the one that downloads from HACS. The one that downloaded is weather-card-chart.js and the one on the github is weather-chart-card.js

**Comment by gdreelin** [comment]
Ok the fix I found was to add the new .js file and rename it to the one in HA. Reboot and then HACS will allow you to reinstall it which fixed the issue. All good now.

**Comment by Yevgenium** [comment]
Oops. Can you check if it works now?

**Comment by gdreelin** [comment]
> 
> 
> Oops. Can you check if it works now?

Well actually I jump for joy too early. It failed again so removed it form HACS then tried to add it back into custom repositories but it will not allow you to add your repository. I was able to do it old school by manually added it back in, but I like to have it linked to HACS to do updates. I love this card too so really want it to work.

**Comment by gdreelin** [comment]
I also tired to clear cache and reboot HA to see if you can link the repository back in but no joy. I put in your url "https://github.com/Yevgenium/weather-chart-card" for Lovelace installment in custom repositories in HACS but it will not add it to the list when it was working before I deleted it to see if I could get it to update to current version. Not sure why it will not add now since it seems to be all correct now.

**Comment by artemyevav** [comment]
There's no file `weather-card-chart.js` in the repo, it was deleted in a9f795f2fd02028bdad9b771d383fa38c5f3148c. Maybe that's the reason?

**Comment by Yevgenium** [comment]
Yes, this was probably the reason. I edited the hacs.json file, hopefully this will fix the problem.

**Comment by gdreelin** [comment]
I just check but no joy. It still will not let you add it to custom repositories in HACS. Honestly not sure why I put in the URL and Lovelace but you click add and nothing. No errors or anything. Manual install works but better if it was in HACS.

**Comment by artemyevav** [comment]
1883526f493b7de2868c7f108da685766a8cc6e9 <-- it works in my repo as expeted. HACS requires the compiled js to exist in the tree. And BTW - your last changes to that file make it failing, I used the js from release 1.0.0

**Comment by gdreelin** [comment]
@artemyevav yeah it did work with your fork without any issues. Only thing is will it have the updates as they are pushed out?

**Comment by artemyevav** [comment]
Nope. I believe you have to put `.js` there manually. Maybe it worth creating smth like `bin` subdir and keep it there.

**Comment by gdreelin** [comment]
@artemyevav yeah that is what I thought. I tried again to get this repo to add but no joy for some reason.

**Comment by artemyevav** [comment]
Reload hass page maybe and clean the cache. It helps sometimes.

**Comment by gdreelin** [comment]
Yeah I did that a few times but same thing. I am just going to use your repo and manually do it.

**Comment by artemyevav** [comment]
The only difference of my repo is https://github.com/artemyevav/weather-chart-card/commit/1883526f493b7de2868c7f108da685766a8cc6e9 which means I got `weather-chart-card.js` from release and put it into  the repo.

**Comment by yan14** [comment]
same here :)

**Comment by artemyevav** [comment]
Hmm. No idea. I've just completely removed it from my HACS and installed it again from my repo - it works.

**Comment by yan14** [comment]
how did you do this? I uninstalled it, then removed the repo, afterwards i added the repo and tried to install it again, but it couldn't finish the load.
I changed my ressources from weather-card-chart to weather-chart-card and my ui-lovelace.yaml, but the card is no showing.

**Comment by artemyevav** [comment]
Try using my fork to see where the problem is: `https://github.com/artemyevav/weather-chart-card`

**Comment by gdreelin** [comment]
It is now working again on this repo so all good now.

**Comment by yan14** [comment]
> 
> 
> It is now working again on this repo so all good now.

it doesn't work for me neither. How did you get it to work?

**Comment by gdreelin** [comment]
@yan14 I close the HA window, cleared all the cache and closed out browser. Once I opened it back up it was all good.

**Comment by Spirituss** [comment]
After upgrade to 1.0.2 it still doesn't work

**Comment by gdreelin** [comment]
I had to completely remove Yevgenium version, clear cache, reboot. Once that is done I just reinstalled it and it started working with all the new chart info. I just did the update and it is still working great.

**Comment by carvalr** [comment]
> I had to completely remove Yevgenium version, clear cache, reboot. Once that is done I just reinstalled it and it started working with all the new chart info. I just did the update and it is still working great.
I did the same and it works perfectly.

**Comment by carvalr** [comment]
> I had to completely remove Yevgenium version, clear cache, reboot. Once that is done I just reinstalled it and it started working with all the new chart info. I just did the update and it is still working great.

I did the same and it works perfectly.

**Comment by X1pheR** [comment]
me too. it works now so this can be closed I guess.
