### ISSUE TITLE
Does not work with swipe card

### ISSUE THREAD

**Issue by jds11111** [Yevgenium/weather-chart-card#66]
This is a beautiful card. I like to use different sources for weather forecasts, and put them in a swipe card.  However, this one does not seem to play well with that.

**Comment by Yevgenium** [comment]
What exactly is the problem? I just configured swipe-card and everything works fine.
![image](https://user-images.githubusercontent.com/33804747/131239098-64c95e50-a5c7-4db9-86b3-8086e0b392f8.png)
![image](https://user-images.githubusercontent.com/33804747/131239115-0fb27184-a20c-47e1-9e3d-e91df31d322a.png)

**Comment by jds11111** [comment]
Huh.  You are right. Must have been some glitch in my lovelace cured by a restart.  Sorry about the unnecessary bother.
