### ISSUE TITLE
Nothing is displayed?

### ISSUE THREAD

**Issue by bussio** [Yevgenium/weather-chart-card#70]
I have included your map via HACS and as in your 1st example (weather.home) in the YAML file. Unfortunately, absolutely nothing is displayed from the map ... 
Do you have any idea what the reason is? 
(HA core-2021.9.0b3, weather-chart-card 1.02)

**Comment by Yevgenium** [comment]
Please provide more information (screenshots, browser console messages, Home Assistant log, etc)

**Comment by bussio** [comment]
Here are 3 snapshots ... 

1. Resources.yaml entry
![resources](https://user-images.githubusercontent.com/48105172/131249042-e01ed511-1fd6-42e4-ade4-9a1c1c02f63d.jpg)

2. Weathercard.yaml entry
![card-config](https://user-images.githubusercontent.com/48105172/131249076-3dedf6f1-0120-4df0-9409-00f73b743ca1.jpg)

3. Dashboard display
![ergebnis](https://user-images.githubusercontent.com/48105172/131249168-6e1c715f-0a7f-4703-bfd2-960aed15bb15.jpg)

Now I have noticed the following. If I change the language in the profile from "German" to "English", then the map is displayed immediately without any problems?!

**Comment by Yevgenium** [comment]
Have you tried clearing your browser cache?

**Comment by bussio** [comment]
I had done that ... now again and strangely enough it now works under the German language, too.
Sorry ... was probably much wind about nothing. Thanks for your effort!
