### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by brandondb1** [Yevgenium/weather-chart-card#73]
Hey, thanks for updating this! It looks better than ever.

In the old version, and now in the new version, I've added the option to define humidity and pressure sensors as well (I have a BME 280 sensor outdoors, so I get temp, pressure and humidity)).

Unfortunately I can't seem to make the code work to default to the weather data if they aren't defined...i..e they come up blank if not defined in the card setup yaml.

I don't know if anyone else would see that as useful...if not I'm OK with what I have. If yes, I have it working minus the default to weather data and could share that with you.

**Comment by Yevgenium** [comment]
In the new version it will be possible to display data from humidity and pressure sensors. If someone considers it necessary, I can add the ability to use sensors for direction and wind speed.

**Comment by Yevgenium** [comment]
I always read the release notes for the new version of Home Assistant, but I didn't know that [this component](https://www.home-assistant.io/integrations/weather.template/) was added. It looks like we don't need sensor support in the weather card.

**Comment by brandondb1** [comment]
Cool.  I hadn't seen that either.  What a great idea!  Also, yes, means no
need to rebuild the card to accomodate sensors.

I guess if it's a template it's perhaps also possible to have multiple
options for the same variable selected based on availability so there's a
'fail safe' option if your local sensor fails.

**Comment by Yevgenium** [comment]
Yes. And we will not see different information about temperature / humidity / etc. on the card and in the more info window, which I did not like and which could confuse new users.
