### ISSUE TITLE
Czech translate, tip for icon download

### ISSUE THREAD

**Issue by matata86** [Yevgenium/weather-chart-card#77]
Hello, thank you for your weather card.

Can you add czech translate please?
`    cs: {
      tempHi: 'Teplota',
      tempLo: 'Teplota v noci',
      precip: 'Srážky',
      uPress: 'hPa',
      uSpeed: 'm/s',
      uPrecip: ['mm', 'in'],
      cardinalDirections: [
        'N', 'N-NE', 'NE', 'E-NE', 'E', 'E-SE', 'SE', 'S-SE',
        'S', 'S-SW', 'SW', 'W-SW', 'W', 'W-NW', 'NW', 'N-NW', 'N'
      ],
      'clear-night': 'Jasná noc',
      'cloudy': 'Zataženo',
      'fog': 'Mlha',
      'hail': 'Kroupy',
      'lightning': 'Bouřky',
      'lightning-rainy': 'Bouřky, déšť',
      'partlycloudy': 'Polojasno',
      'pouring': 'Silný déť',
      'rainy': 'Déšť',
      'snowy': 'Sníh',
      'snowy-rainy': 'Sníh s deštěm',
      'sunny': 'Jasno',
      'windy': 'Větrno',
      'windy-variant': 'Větrno'
    },`

Do you have some tip, where download nice weather icons?

**Comment by Yevgenium** [comment]
> Can you add czech translate please?

Added in v1.1.0
