### ISSUE TITLE
FR: German localization

### ISSUE THREAD

**Issue by marcokitzmann** [Yevgenium/weather-chart-card#80]
It would be nice to add german translation. Tried it by myself by adding this to the locale const, but with no effect:

de: {
      'tempHi': 'Temperatur',
      'tempLo': 'Nachttemperatur',
      'precip': 'Niederschlag',
      'units': {
        'km/h': 'km/h',
        'm/s': 'm/s',
        'hPa': 'hPa',
        'mmHg': 'mm Hg',
        'mm': 'mm',
        'in': 'in'
      },
      'cardinalDirections': [
        'N', 'N-NO', 'NO', 'O-NO', 'O', 'O-SO', 'SO', 'S-SO',
        'S', 'S-SW', 'SW', 'W-SW', 'W', 'W-NW', 'NW', 'N-NW', 'N'
      ],
      'clear-night': 'Sternenklar',
      'cloudy': 'Bewölkt',
      'fog': 'Nebel',
      'hail': 'Hagel',
      'lightning': 'Gewitter',
      'lightning-rainy': 'Gewitter, Regen',
      'partlycloudy': 'Teils bewölkt',
      'pouring': 'Starkregen',
      'rainy': 'Regen',
      'snowy': 'Schnee',
      'snowy-rainy': 'Schneeregen',
      'sunny': 'Sonne',
      'windy': 'Windig',
      'windy-variant': 'Windig'
    },

 Strange. I leave it here, maybe you can use it.

**Comment by Yevgenium** [comment]
Will be available in the next update. Thanks!

![image](https://user-images.githubusercontent.com/33804747/145156976-053c8773-90de-42ea-9b27-2d8cb51936c0.png)
