### ISSUE TITLE
Precision of pressure

### ISSUE THREAD

**Issue by backcountrymountains** [Yevgenium/weather-chart-card#90]
The default precision of the pressure reading from OpenWeatherMap is a bit high. I was wondering if you could round it down a bit.

I just installed the card and with the default settings of the card and the values from OpenWeatherMap, my pressure is '29.500450184547606 hPa' I'm impressed with the ability of the OpenWeatherMap people to measure barometric pressure at an apparently molecular level, but it somewhat clutters the card.

Not really an issue, but I wanted to thank you for making the card; it's great!

**Comment by fmonday** [comment]
Have noticed this as well- OWM is providing the data in hPa and doing the math of converting it to mmHg but without rounding.

**Comment by Yevgenium** [comment]
Fixed in 1.2.0
