### ISSUE TITLE
Problem with lovelace card generation

### ISSUE THREAD

**Issue by Palpyroth** [Yevgenium/weather-chart-card#91]
Hello, 
I'm a noob in HA but I want to do 2 weather cards like
![image](https://user-images.githubusercontent.com/97630633/149666716-14da0f94-5a3c-4bb8-b5ea-5cd5567b0b75.png)
and the same but hourly.

When I follow the readme I've this result
![image](https://user-images.githubusercontent.com/97630633/149666697-2308ffb1-a9aa-4b39-9592-a931696731b3.png)
I miss forecast low temp and precipitation

> type: custom:weather-chart-card
> entity: weather.openweathermap
> show_main: true
> show_attributes: true

I try to change entity but the only weather entity I've is openweathermap (cant use sensor entity)
Can someone healp me?

thank you

**Comment by Yevgenium** [comment]
Hourly forecast does not provide low temp.
