### ISSUE TITLE
temperature1_color not changing on iPad

### ISSUE THREAD

**Issue by tomlut** [Yevgenium/weather-chart-card#96]
Using the following configuration:

```
type: custom:weather-chart-card
entity: weather.weatherflow_day_based_forecast
show_main: false
show_attributes: false
title: Daily Forecast
temperature1_color: rgba(228, 94, 101, 1.0)

```

I get a red first temperature line on my desktop PC (Firefox and Chrome) and in the iOS app on my phone but for my iPad Pro the first line colour remains as orange. 

I have tried resetting the frontend cache in the app debug settings then pulling down on the page to refresh it, but this makes no difference.

**Comment by Yevgenium** [comment]
Forecast options including chart colors now in the `forecast` block. In your case, the configuration will look like this:
```
type: custom:weather-chart-card
entity: weather.weatherflow_day_based_forecast
show_main: false
show_attributes: false
title: Daily Forecast
forecast:
  temperature1_color: rgba(228, 94, 101, 1.0)
```
[Configuration variables](https://github.com/Yevgenium/weather-chart-card#configuration-variables)

**Comment by tomlut** [comment]
Thanks, that fixed it.
